### ISSUE TITLE
Sometimes getting `Path does not exist`

### ISSUE THREAD

**Issue by OfficialEsco** [ItzLevvie/winget-pkgs-validate-and-install#2]
@ItzLevvie do you know the reason for this?

```
Enter a pull request number: 36963

Path does not exist: C:\Users\User\Documents\GitHub\winget-pkgs\manifests\n\nathancorvussolis\corvusskk\3.1.2\nathancorvussolis.corvusskk.installer.yaml"
Path does not exist: C:\Users\User\Documents\GitHub\winget-pkgs\manifests\n\nathancorvussolis\corvusskk\3.1.2\nathancorvussolis.corvusskk.installer.yaml"

Press any key to continue . . .
```

**Comment by ItzLevvie** [comment]
Script uses the bugged WinGet version 1.1.12701 which doesn't validate PRs with 3010 as InstallerSuccessCodes, so it errors out.

You're getting `Path does not exist` because the script uses `winget validate` to try and find the path based on winget validate's %ERRORLEVEL% but since WinGet is bugged, the script cannot find the path.

It should be fixed in the latest update.
